version: '3.3'
services:
  school-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db-school'
      MYSQL_USER: 'school'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:      
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-school:/var/lib/mysql
volumes:
  mysql-school: